apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 3  # Number of copies of the app to run
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: shreyasingh21/fastapi_webserver:v2  # Your Docker image
        ports:
        - containerPort: 80  # Port your app listens on
