apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # Number of pods to run
  strategy:
    type: RollingUpdate  # This is the default strategy
    rollingUpdate:
      maxSurge: 1  # Number of extra pods to bring up during update
      maxUnavailable: 0  # Ensure no pods are terminated until the new one is running
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:1.19  # Image of the app
